#!/usr/bin/env bash
# Configures localhost and facebook.com IP resolution
sed 's/127\.0\.0\.1 localhost/127.0.0.2 localhost/' /etc/hosts > /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts
rm /tmp/hosts
