#!/usr/bin/env bash
# Configures localhost and facebook.com IP resolution
sed 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts > /tmp/hosts
cat /tmp/hosts > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
rm -f /tmp/hosts
